<?php

namespace App\Models\Hospitalisation;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class thospi_transfusion_surveil extends Model
{
    protected $fillable=
    [       'id',
            'refSurvHospi',
            'dateTransfusion',
            'heureDebut',
            'heureFin',
            'status',
            'Nmpoche',
            'dateperemption',
            'medecinDemandeur',
            'nombre',
            'reatianTransttut',
            'dysphee1',
            'ExtrenateCyanosee',
            'tachycardie',
            'paleurcutaneo',
            'extremitesfoides',
            'TA_transf',
            'agitation',
            'autres1',
            'indicationTransf',
            'Hb_avant',
            'hct_avant',
            'Hb_apres',
            'hct_apres',
            'qteSangTransfuse',
            'nature',
            'hbTransfusion',
            'hct_transfusion',
            'compatible',
            'temperatureSurv',
            'FRtraitSurv',
            'FCtraitSurv',
            'TAtraitSurv',
            'autres2',
            'rashCutane',
            'frisson',
            'troubleRythme',
            'nausee',
            'temperature2',
            'TA2',
            'FR2',
            'oedemelaynge1',
            'diarhee',
            'oedemelaynge2',
            'dysphee2',
            'pouls_0a15min',
            'douleurabdominal',
            'precardialge',
            'lambelgue',
            'TA_15a30',
            'temperature_15a30',
            'pauls_15a30',
            'fr_15a30',
            'autres3',
            'observation1',
            'ta_30a1_heure',
            'tempera_30a1_heure',
            'pauls_30a1heure',
            'fr_30a1heure',
            'autres4',
            'observation2',
            'TA_1a2h',
            'Pouls_1a2h',
            'Temperature_1a2h',
            'FR_1a2h',
            'autres_1a2h',
            'observations_1a2h',
            'TA_2ha3h',
            'temperature_2ha3h',
            'pauls_2ha3h',
            'fr_2ha3h',
            'observation3',
            'autres5',
            'autres_2ha3h',
            'observationsGenol',
            'author'
    ];
    protected $table = 'thospi_transfusion_surveil';
}
