<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTconfMedicamentTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tconf_medicament', function (Blueprint $table) {
            $table->id();
            $table->string('nom_medicament', 250);  
            $table->foreignId('refcategoriemedicament')->constrained('tconf_categoriemedicament')->restrictOnUpdate()->restrictOnDelete();
            $table->double('pu_medicament')->default(0); 
            $table->string('forme', 250)->default('PCS');  
            $table->double('qtetot')->default(0);   
            $table->double('stock_alerte')->default(2);       
            $table->string('author')->default('Admin');
            $table->string('deleted')->default('NON');
            $table->string('author_deleted')->default('user'); 
            $table->timestamps();
        });

        DB::table('tconf_medicament')->insert([
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ASPIRINE 500MG  500MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ASPIRINE 500MG USPA EFF.'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ABAISSE LANGUE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ACTAPULGITE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ADALATE 10MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ADALATE 20MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'A-DEM CRÈME 15GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'A-DEM CRÈME 30GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'A-DEM FEMINA LOTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ADRENALINE INJECTABL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AERIUS 5MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AERIUS SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AGUILLE A PL G22'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AIGUILLE A PL G25'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALAISE SACHETS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALAISE SACHETS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALBENDAZOL 400MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALBENDAZOLE 400MG SP 10M'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALDOMET 250MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALZIT 500MG 3CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMBROLITE SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMIDOL COLD 4CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMINOPHYLLINE 100MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMITONE SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMLODENK 10MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMLODENK 5MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMOXYCILLINE 125MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMOXYCILLINE 1GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMOXYCILLINE 250/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMOXYCILLINE 250MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMOXYCILLINE 500MG CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AMPICYLLINE 1GR INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANAFLAM CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANAFLAM SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANSET    SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANSET 2MG/ML INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANSET 4MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANSET SP 30ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ANTALGEX CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARAUBACT 500MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARAUBACT INFUSION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARAUCLAV 562,50MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARAUCOLD CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARAUFIX SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARAULAV  312,5MG/5ML SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARGYROL GOUTTE 10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARODERME POUDRE 50GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AROGYL OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARTEQUICK 4CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARTESUNAT 60MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARTESUNATE 150MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARTESUNATE 180MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARTESUNATE 240MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ARTESUNATE 30MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ASTYMIN SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ATROPINE  INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AUGMENTIN INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AUGMENTIN STEROP CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AUGMENTIN STEROP SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AVAMYS SPRAY'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AZITHROMYCINE  SP 30ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AZITHROMYCINE 250MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AZITHROMYCINE 500MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BACTRIM SP 240MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BANDE ELASTIC 15CM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BANDE ELASTIC 15CM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BANDE ELASTIC 15CM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BANDE PLATREE 20CM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BAUME DE NERF'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BENZOATE  D’OEUSTRADIOL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BETNEVAL CREME'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BICARBONATE DE NA'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BICARBONATE DE NA'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BIPIVACAINE AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BISACODYL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BISTOURIE N0 15'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BISTOURIE N0 22'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BROCANLENE SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BROCHIDIAZINA SP 150ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BRONCALENE ENFANT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'BROZEDEX SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CADIPHEN SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CALCIUM 1G/10ML  INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CALD 500MG/250UI CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CANDERM POUDRE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CANDISTEN CRÈME 30GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CAPTOPRIL 25MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CARDIOASPIRINE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CARTIL CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CAT GUT(TOUT)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CATHÉTER  G22'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CATHÉTER G18'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CATHÉTER G24'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEDOCAR 5MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFALEXIME 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFALEXINE 250MG SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFAM CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFIXIME 200MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFIXIME 400MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFOTAXIME 1GR INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFRIAXONE PLUS 1,50GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFTRIAXONE SIMPLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CELESTENE AMPOULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CELESTENE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CELESTENE GTTE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEMYCINE 100MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEMYCINE 500MG 5CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CETHER L CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CETHER-L SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CETRIMEX 10MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CHLORPHENIRAMINE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CHLORPROMAZINE 50MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIFIN-DX  COLLYRE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIMETIDINE 200MG/2ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIMETIDINE 400MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIPRO INFUSION 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIPROFLOXACINE  500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIPROFLOXACINE SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIPROHEPTADINE SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLAFORAN INJ 1GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLAMOXYL 125MG/5ML 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLAMOXYL 250MG/5ML 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLAMOXYL 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLARINEZ 0,05%'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLARINEZ 0,1%'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLINDAMYCINE 150MG CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLINDAMYCINE 150MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLINDAMYCINE 300MG CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLINDAMYCINE 300MG INJEC'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLINDAMYCINE 600MG CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLOMID  50MG 10CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLORAMINE 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLOXACILLINE 125MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLOXACILLINE 250MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLOXACILLINE 250MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CLOXACILLINE 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COARTLUF SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COATEM 24CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COLD GRIPPE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COMPRESSE 1,50MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CORIMETHAR 6CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CORIMETHAR SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CORTISTAR SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COSODRYL 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COTRIMOXAXOLE  480MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COTRIMOXAXOLE  960MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CURAM 625MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CURAM SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CYCLOMAX OVUL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CYTOTEC 200(MISOPROSTOL)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DAONIL 5MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEBRIDAT SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DECONTACTYL  CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEPAKINE 57,5MG/ML 150ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DERMACIDAL SOLUTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DERMOBACTER 125ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DERMOBACTER 250ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DESLORA 5MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEXAMETHAZONE 4MG  INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEXAMETHAZONE 4MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEXOL CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEXOL SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DEXTROSE 50% 50ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DIAZEPAM 10MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DIAZÉPAM10MG/2ML INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DICLOFENAC  50MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DICLOFENAC  SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DICLOFENAC 75MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DICLOFENAC DREME 30GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DOLAREN PLUS CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DOLAREN RAPIDE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DOLAREN SPRAY'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DOXY 100MG GEL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DR COLD SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DUPHALAC SACHETS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DUPHALAC SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DYCYNONE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DYNAMOGENE AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EAU DIGESTIVE 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EAU DISTILLÉE 10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EFFERALGAN 16CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EFFERALGAN SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EFISHAL 200MG GEL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EJUTARD 30MG 2CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ENALAPRIL 10MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ENALAPRIL 5MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EPHEDRINE AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ERGOMETRINE 0,50MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ERGOMETRINE0,5MG  INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ERYTHRO 250MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ERYTHROMYCINE 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ERYTHROMYCINE SP 250MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ERYTHROMYCINE SP 250MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ESIDREX 25MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ESMODOM 40/30MG GEL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ESOMEX 40MG INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ESOQUE 40MG INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EXACYL AMPOU INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'EXACYL AMPOULE BUVABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FALOR LOTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FEBRILEX SP 150ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FEFOL CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FELDEN SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FEMACLIN OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FEMMEX CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FENAMEX CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FENTANYL AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FLUCASOL SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FLUCODEX CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FLUOMYSIN CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FUNBACT CREME'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FUNBACT SAVON'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FURANDANTINE 100MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FUROZEMIDE 40MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'FUROZEMIDE INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GAMATATE B6 CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GAMATATE B6 SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GANT PROPRE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GANT STÉRILE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GENTAMICINE 80MG/2ML INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GERMOL LIQUIDE 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GERMOL SAVON 125GM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GERMOL SAVON 75GM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GLUCOSE 5% 500ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GLYCERINE PHENIQUE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GOGYNAX'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GOGYNAX OV'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GRIPPAL ADULTE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GRIPPAL ENFANT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GRIPPAL NOURRISSON'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GRISEOFULVINE 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GYNOKLEEN LOTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HAEM PLUS 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HALOTHANE SOLUTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HEMACEL 500ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HEMOROIDAL HC SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HEMOROIDAL SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HEPTIN PLUS CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HEPTIN PLUS SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HEXTRIL SOLUTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HIFER CES A SUCER'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HIFER Z SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HP-3KIT CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HYDROCORTISONE 100GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HYDROCORTISONE CREME'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'HYPARTIL PLUS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IBUPAR SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IBUPROFEN  SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IBUPROFEN 200MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IBUPROFEN 400MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'INDOCID 100MG SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IPROSEC CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IPROSEC -D'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'IPROSEC INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'KAOLIN SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'KAPTOL SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'KCL AMP 1GR/10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'KETAMINE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'KETAZOL 200MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'KETAZOL CRÈME 30GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'L-ARTEM  FORTE 6CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LIDOCAINE  INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LOPRADE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LORATOL 10MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LORATOL SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LUTENYL CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MAGNAVIT CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MAGNAVIT SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MALADOX 525MG 3CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MALDON CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MAXIDROL COLLYRE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MEDIVEN CREME 15GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MENTRIL SOLUTION 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MEPROBAMATE 400MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'METOCLOPRAMIDE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'METOCLOPRAMIDE INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'METRO INFUSION 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'METRONIDAZOLE 125MG/5ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'METRONIDAZOLE 250MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'METRONIDAZOLE 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MICROLAX BEBE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MOTILLIUM SIROP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MOXICLAV DUO 1000MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MOXICLAV DUO 562,50MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MOXICLAV SP 70ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MUCOCLER SP ADULTE 150ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MUCOCLER SP ENFANT 150ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MUCOPRIN SP ADULTE 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MUCOPRIN SP ENFANT 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MULTI VIT 100ML  SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MULTI VIT CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MYCORIL SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'MYCOSEMA  CREME 30GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NACL 1G/10ML  AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NASONEX SPRAY'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NEUROCARE FORTE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NEWMEX FORTE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NOCOLD CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NORFALAGYL 250/400MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NORFLAGYL 100/100MG SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NORMEGYL 100/100MG SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NUCLEO CMP CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NUTRISANG SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NYLON (TOUT)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NYSTALINE 100000UI SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NYSTATINE  OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NYSTATINE 500000UI'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OCYTOCINE INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OMEKAR 40MG INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OMEPRAZOLE 20MG CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ONDACET 4MG INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ONDACET SPRAY'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OTRINIQUE 0.05% 10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OTRINIQUE 0.1% 10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OUATE 100GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OVOGYL OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OVUMIX OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PA C SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PA-12 CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PAIDOTÉRIN 100ML SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PANCURONIUM AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PAPAVÉRINE 40MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PAPAVERINE40ML/ML  INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PARACÉTAMOL CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PARACÉTAMOL INJ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PARACÉTAMOL SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PARACÉTAMOL SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PARAVIT C SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PEDIPHEN SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PERFAC 1000MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PERFAC 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PERFAC C 500/200MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PERFALGAN INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PERMANGANATE 500MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PEROXYDE 2% 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PHÉNOBARBITAL 100MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PHÉNOBARBITAL INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POLYGEL DUAL 120ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POLYGEL SP 120ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POLYGEL SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POLYGYNAX'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POMADE CAMPHRÉE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POMADE CHRYSOPHANIQUE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POMADE DITHRANOL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POMADE ICHTYOLÉE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POSITON CREME'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POTENTIATOR AMP BUV'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POUDRE EXOPHEN'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POVIDONE IODINE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PRAZOL 40MG INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PREDNISOLONE 5MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PRENATAL DENK'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PRENATAL DENK DHA'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PRIMALAN SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROGESTERONE INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROLENE(T0UT)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROMÉTHAZINE 25MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROMÉTHAZINE INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROMÉTHAZINE SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROMÉTHAZINE SP EX 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PROPOFOL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'QUININE 20% 10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'QUININE 300MG/ML INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'QUININE 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'QUININE 500MG/2ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'RANITIDINE INJECT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'RECTAIDE HC'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'RHINATIOL SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'RINATHIOLOL+PROMRTHAZ.'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'RINGER LACTATE 500ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SAC COLLECTEUR(URIFLAC)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SALBUTAMOL  SPRAY'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SALBUTAMOL INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SALBUTAMOL SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SALBUTAMOL SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SAT AMP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SEKROL SP ADULTE 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SEKROL SP ENFANT  100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SERINGUE 10CC'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SERINGUE 2CC'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SERINGUE 5CC'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SERINGUE À INSUL.'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SÉRUM PHYSIOLOGIQUE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SHALDEX 10ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SMECTA SACHET'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SOL.  PHYSIOLOGIQUE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SOLUDENT SOLUTION 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SONDE NASO-GASTR.'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SONDE URINAIRE (TN)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SPARADRAP  P.'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SPARET FORTE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SPARET GOUTTE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SPASFON  80MG SUPPO'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SPASFON 40MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SPASFON INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SRO SACHETS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'STERIMAR SPRAY'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'STÉROVIT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SULFATE DE ZINC'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SULPHATE DE MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SUPER APPETIT SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SUXAMETHONIUM'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TANZOL 400MG CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TANZOL SP'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TAZEX 1125MG INJECR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TETRA OPHTALMIQUE 6GR'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'THERMOMÈTRE À MERCURE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'THIAMINE INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TINIDAZOLE CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TRAMADOL 50MG CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TRAMADOL INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TRAVISIL SP 200ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TRIAM DENK'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TRIBEX FORT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TRIOKIT CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TROIS FORT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TROIS FORT INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TROUSSE À PERFUSION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'TUGERME CREME'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ULTRA DOZEM CES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ULTRA LEVURE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'UTROGESTAN'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'UTROGESTAN OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VAGIKLIN OVULE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VENTOLIN POUR NEBUL.'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VENTOLINE SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VERMOX 100MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VERMOX 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VERMOX SP 30ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VICRYL (TOUT)'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT B1 100MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT B6 50MG CE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT B6 INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT C 500MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT C INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT C SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT K1 INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VIT K3 INJECTABLE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'V-LAVAGE LOTION'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VOMARET SP 30ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ZINC SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ZITHRO PLUS SP 30ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AUTRES'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Doliprane'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Spascol'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OFLOQUE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COMBUSUNATE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SOCOMOL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'SUNITAB'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PRAZOL KIT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'POLIKIT'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Nocygel sirop'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Macalum'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Pregabaline'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Ofloque oz sp'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Lutter sp'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Cefixime sp'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Spasta sp'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Neodexa collyr'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Uniclav sp enfant'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Uniclav sp nourisson'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Spascol'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'AKEROL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Uniclav'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'NECLAZ 40MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GYNODAKTARIN GEL ORAL'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Autobiotic goutte'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Otobiotic goutte'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OFLOQUE OZ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'OFLOQUE OZ'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Esomex comprimé'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Decaris'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CIPRONATE'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Levofloxacin'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Uniclave siron enfants et nourisson'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Moxiclave siron enfants et nourisson'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Celesten goûtte'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Citron z goute'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Vitrau'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Pretigestant ovule'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Vivagest'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Miorel'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LUTHER SP 60ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'PRAZOL D CAPS'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Plâtre'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Moxyclav'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'Prescription non medicamentée'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'COMBUSUNATE 5 a 15KG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'ALCOOL DENATURE 5L'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GRIPPAL ADULTE SP 100ML'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DUPHASTON 10 MG Ces'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'LUTHENYL Ces'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'CEFUROCLAV 625 MG Ces'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VASOCAR 5 MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VASOCAR T'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'VASOCAR TH'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GLIBEN - M Ces'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GLUCOPHASE 850 MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'GLUCOPHASE 500 MG'],
            ['refcategoriemedicament' =>1,'nom_medicament' => 'DAONIL 5 MG Ces']
        ]);






    }

    //

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tconf_medicament');
    }
}
