<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAvenuesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('avenues', function (Blueprint $table) {
            $table->id();
            $table->foreignId('idQuartier')->constrained('quartiers')->restrictOnUpdate()->restrictOnDelete();
            $table->string('nomAvenue', 250);
            $table->timestamps();
        });

        DB::table('avenues')->insert([
            ['idQuartier' =>1,'nomAvenue' => 'DU LAC'],
            ['idQuartier' =>1,'nomAvenue' => 'DE LA MISSION'],
            ['idQuartier' =>1,'nomAvenue' => 'DE LA FRONTIERE'],
            ['idQuartier' =>2,'nomAvenue' => 'BOBILADAWA'],
            ['idQuartier' =>2,'nomAvenue' => 'KITUKU'],
            ['idQuartier' =>3,'nomAvenue' => 'LE VOLCAN'],
            ['idQuartier' =>4,'nomAvenue' => 'NDOSHO'],
            ['idQuartier' =>5,'nomAvenue' => 'KATINDO2'],
            ['idQuartier' =>5,'nomAvenue' => 'MABANGA-SUD'],
            ['idQuartier' =>5,'nomAvenue' => 'MAJENGO'],
            ['idQuartier' =>5,'nomAvenue' => 'KATOYI'],
            ['idQuartier' =>12,'nomAvenue' => 'WALIKALE'],
            ['idQuartier' =>12,'nomAvenue' => 'UVIRA'],
            ['idQuartier' =>18,'nomAvenue' => 'NYAKAKOMA'],
            ['idQuartier' =>11,'nomAvenue' => 'MANIEMA'],
            ['idQuartier' =>11,'nomAvenue' => 'BENI'],
            ['idQuartier' =>11,'nomAvenue' => 'CARMEL'],
            ['idQuartier' =>11,'nomAvenue' => 'MASISI'],
            ['idQuartier' =>11,'nomAvenue' => 'DU LAC'],
            ['idQuartier' =>11,'nomAvenue' => 'ISHASHA'],
            ['idQuartier' =>11,'nomAvenue' => 'LA FRONTIERE'],
            ['idQuartier' =>11,'nomAvenue' => 'BUNAGANA'],
            ['idQuartier' =>2,'nomAvenue' => 'MAENDELEO'],
            ['idQuartier' =>2,'nomAvenue' => 'LEMERA'],
            ['idQuartier' =>2,'nomAvenue' => 'KIBATI'],
            ['idQuartier' =>2,'nomAvenue' => 'NZIYUMVIRA'],
            ['idQuartier' =>2,'nomAvenue' => 'DU LAC 1'],
            ['idQuartier' =>2,'nomAvenue' => 'DE SPORT'],
            ['idQuartier' =>2,'nomAvenue' => 'KESHERO 1'],
            ['idQuartier' =>2,'nomAvenue' => 'AMANI'],
            ['idQuartier' =>2,'nomAvenue' => 'AMANI'],
            ['idQuartier' =>2,'nomAvenue' => 'ABATTOIR'],
            ['idQuartier' =>2,'nomAvenue' => 'KIZITO'],
            ['idQuartier' =>2,'nomAvenue' => 'DU LAC 3'],
            ['idQuartier' =>2,'nomAvenue' => 'MUSIENENE'],
            ['idQuartier' =>2,'nomAvenue' => 'BUKAMA SUD'],
            ['idQuartier' =>2,'nomAvenue' => 'BUKAMA NORD'],
            ['idQuartier' =>2,'nomAvenue' => 'KITUKU 1'],
            ['idQuartier' =>2,'nomAvenue' => 'KITUKU 2'],
            ['idQuartier' =>8,'nomAvenue' => 'BUKONDE'],
            ['idQuartier' =>2,'nomAvenue' => 'IRENGETI'],
            ['idQuartier' =>13,'nomAvenue' => 'BURUNGU'],
            ['idQuartier' =>13,'nomAvenue' => 'MABANGA'],
            ['idQuartier' =>13,'nomAvenue' => 'MAJENGO'],
            ['idQuartier' =>13,'nomAvenue' => 'KIMBANGUISTE'],
            ['idQuartier' =>1,'nomAvenue' => 'WALIKALE'],
            ['idQuartier' =>13,'nomAvenue' => 'CCLK'],
            ['idQuartier' =>13,'nomAvenue' => 'KATWA'],
            ['idQuartier' =>10,'nomAvenue' => 'MINOVA'],
            ['idQuartier' =>10,'nomAvenue' => 'MWANGAZA'],
            ['idQuartier' =>13,'nomAvenue' => 'IDJWI'],
            ['idQuartier' =>10,'nomAvenue' => 'RUZIZI'],
            ['idQuartier' =>10,'nomAvenue' => 'RUMANGABO'],
            ['idQuartier' =>1,'nomAvenue' => '30 JUIN'],
            ['idQuartier' =>8,'nomAvenue' => 'PINGA'],
            ['idQuartier' =>8,'nomAvenue' => 'VITSHUMBI 1'],
            ['idQuartier' =>18,'nomAvenue' => 'VITSHUMBI 2'],
            ['idQuartier' =>18,'nomAvenue' => 'VISOKE'],
            ['idQuartier' =>18,'nomAvenue' => 'KILIMANJARO 2'],
            ['idQuartier' =>18,'nomAvenue' => 'KASINDI 1'],
            ['idQuartier' =>18,'nomAvenue' => 'KASINDI 2'],
            ['idQuartier' =>18,'nomAvenue' => 'KASINDI 3'],
            ['idQuartier' =>6,'nomAvenue' => 'KINSHASA'],
            ['idQuartier' =>6,'nomAvenue' => 'MUSHUNGANYA'],
            ['idQuartier' =>6,'nomAvenue' => 'NDALAGA'],
            ['idQuartier' =>6,'nomAvenue' => 'AMANI'],
            ['idQuartier' =>6,'nomAvenue' => 'RUTOBOGO'],
            ['idQuartier' =>6,'nomAvenue' => 'CIRCULAIRE'],
            ['idQuartier' =>6,'nomAvenue' => 'RUYANGE'],
            ['idQuartier' =>4,'nomAvenue' => 'RULENGA'],
            ['idQuartier' =>4,'nomAvenue' => 'KITO'],
            ['idQuartier' =>4,'nomAvenue' => 'DE LA CARRIERE'],
            ['idQuartier' =>4,'nomAvenue' => 'DE LA DEMOCRATIE'],
            ['idQuartier' =>4,'nomAvenue' => 'UBANGI'],
            ['idQuartier' =>4,'nomAvenue' => 'UBANGI'],
            ['idQuartier' =>4,'nomAvenue' => 'KALONJI'],
            ['idQuartier' =>17,'nomAvenue' => 'MULAMBA'],
            ['idQuartier' =>17,'nomAvenue' => 'POTOPOTO'],
            ['idQuartier' =>17,'nomAvenue' => 'BIGARUKA'],
            ['idQuartier' =>17,'nomAvenue' => 'SEMULIKI'],
            ['idQuartier' =>17,'nomAvenue' => 'DU PARC'],
            ['idQuartier' =>17,'nomAvenue' => 'VIRUNGA'],
            ['idQuartier' =>1,'nomAvenue' => 'DE LA PAIX'],
            ['idQuartier' =>15,'nomAvenue' => 'MUDIAYI'],
            ['idQuartier' =>15,'nomAvenue' => 'DIKUTA'],
            ['idQuartier' =>16,'nomAvenue' => 'HAUT-CONGO'],
            ['idQuartier' =>16,'nomAvenue' => 'HAUT-CONGO'],
            ['idQuartier' =>15,'nomAvenue' => 'NYAMASEKO'],
            ['idQuartier' =>15,'nomAvenue' => 'GL MULAMBA'],
            ['idQuartier' =>16,'nomAvenue' => 'COOPERATIVE'],
            ['idQuartier' =>15,'nomAvenue' => 'LEMBI'],
            ['idQuartier' =>16,'nomAvenue' => 'NYAMULAGIRA'],
            ['idQuartier' =>16,'nomAvenue' => 'LOWA'],
            ['idQuartier' =>15,'nomAvenue' => 'BOTETI'],
            ['idQuartier' =>16,'nomAvenue' => 'DE LA PLAINE SUD'],
            ['idQuartier' =>15,'nomAvenue' => 'BOTETI'],
            ['idQuartier' =>16,'nomAvenue' => 'DE LA PLAINE NORD'],
            ['idQuartier' =>16,'nomAvenue' => 'DU MARCHE'],
            ['idQuartier' =>15,'nomAvenue' => 'MUTSHATSHA'],
            ['idQuartier' =>16,'nomAvenue' => 'DU COLLEGE'],
            ['idQuartier' =>15,'nomAvenue' => 'BOBOZO'],
            ['idQuartier' =>16,'nomAvenue' => 'UELE'],
            ['idQuartier' =>15,'nomAvenue' => 'KIBATI'],
            ['idQuartier' =>16,'nomAvenue' => 'BANANIER'],
            ['idQuartier' =>15,'nomAvenue' => 'DU FLEUVE'],
            ['idQuartier' =>15,'nomAvenue' => 'MULIGE'],
            ['idQuartier' =>15,'nomAvenue' => 'KABEGA'],
            ['idQuartier' =>16,'nomAvenue' => 'RWENZORI'],
            ['idQuartier' =>16,'nomAvenue' => 'LAC VERT'],
            ['idQuartier' =>16,'nomAvenue' => 'LAC KIVU'],
            ['idQuartier' =>16,'nomAvenue' => 'DU COMMERCE'],
            ['idQuartier' =>15,'nomAvenue' => 'KASIKA'],
            ['idQuartier' =>15,'nomAvenue' => 'MBATI'],
            ['idQuartier' =>16,'nomAvenue' => 'NYIRAGONGO 1'],
            ['idQuartier' =>15,'nomAvenue' => 'MBATI'],
            ['idQuartier' =>16,'nomAvenue' => 'MIKENO'],
            ['idQuartier' =>16,'nomAvenue' => 'MANIEMA'],
            ['idQuartier' =>15,'nomAvenue' => 'ITALA'],
            ['idQuartier' =>16,'nomAvenue' => 'ACCASSIAS'],
            ['idQuartier' =>15,'nomAvenue' => 'MONT-BLEU'],
            ['idQuartier' =>16,'nomAvenue' => 'LOASHI'],
            ['idQuartier' =>15,'nomAvenue' => 'BWISHA'],
            ['idQuartier' =>16,'nomAvenue' => 'KABARE'],
            ['idQuartier' =>15,'nomAvenue' => 'DES GEOMETRES I'],
            ['idQuartier' =>16,'nomAvenue' => 'PANGI'],
            ['idQuartier' =>15,'nomAvenue' => 'RWINDI'],
            ['idQuartier' =>15,'nomAvenue' => 'KIRUMBA'],
            ['idQuartier' =>15,'nomAvenue' => 'LUALABA'],
            ['idQuartier' =>15,'nomAvenue' => 'NYAKAKOMA'],
            ['idQuartier' =>15,'nomAvenue' => 'KILIMANYOKA'],
            ['idQuartier' =>15,'nomAvenue' => 'KATOYI'],
            ['idQuartier' =>16,'nomAvenue' => 'UVIRA'],
            ['idQuartier' =>16,'nomAvenue' => 'UVIRA'],
            ['idQuartier' =>15,'nomAvenue' => 'LUKWETI'],
            ['idQuartier' =>15,'nomAvenue' => 'LUOTU'],
            ['idQuartier' =>16,'nomAvenue' => 'UVIRA'],
            ['idQuartier' =>15,'nomAvenue' => 'MWESO'],
            ['idQuartier' =>16,'nomAvenue' => 'KASAVUBU'],
            ['idQuartier' =>15,'nomAvenue' => 'BAMATE'],
            ['idQuartier' =>16,'nomAvenue' => 'LUMUMBA'],
            ['idQuartier' =>15,'nomAvenue' => 'NGULO'],
            ['idQuartier' =>16,'nomAvenue' => 'NYIRAGONGO 2'],
            ['idQuartier' =>15,'nomAvenue' => 'BIKINGWE'],
            ['idQuartier' =>16,'nomAvenue' => 'MUKOSASENGE'],
            ['idQuartier' =>15,'nomAvenue' => 'NYANDONDO'],
            ['idQuartier' =>16,'nomAvenue' => 'BUNIA'],
            ['idQuartier' =>16,'nomAvenue' => 'TSHELA'],
            ['idQuartier' =>15,'nomAvenue' => 'KYAMBOGHO'],
            ['idQuartier' =>16,'nomAvenue' => 'NDURUMO'],
            ['idQuartier' =>15,'nomAvenue' => 'BAKISI'],
            ['idQuartier' =>16,'nomAvenue' => 'FIKIRI'],
            ['idQuartier' =>15,'nomAvenue' => 'DES GEOMETRIES II'],
            ['idQuartier' =>15,'nomAvenue' => 'TONGIL'],
            ['idQuartier' =>19,'nomAvenue' => 'BUNYEREZO'],
            ['idQuartier' =>19,'nomAvenue' => 'BULENGERA'],
            ['idQuartier' =>14,'nomAvenue' => 'KANYAMANJANJA'],
            ['idQuartier' =>14,'nomAvenue' => 'BAHIZI'],
            ['idQuartier' =>14,'nomAvenue' => 'BAHIZI'],
            ['idQuartier' =>15,'nomAvenue' => 'MIKUNDI I'],
            ['idQuartier' =>7,'nomAvenue' => 'KIMUTI'],
            ['idQuartier' =>14,'nomAvenue' => 'MIKUNDI II'],
            ['idQuartier' =>14,'nomAvenue' => 'MIKUNDI II'],
            ['idQuartier' =>19,'nomAvenue' => 'BULENGERA'],
            ['idQuartier' =>19,'nomAvenue' => 'JOLIS BOIS'],
            ['idQuartier' =>14,'nomAvenue' => 'DU 4 JANVIER'],
            ['idQuartier' =>19,'nomAvenue' => 'HANIKA'],
            ['idQuartier' =>14,'nomAvenue' => 'LA RWINDI'],
            ['idQuartier' =>19,'nomAvenue' => 'BUHIMBA'],
            ['idQuartier' =>14,'nomAvenue' => 'LUBERO'],
            ['idQuartier' =>19,'nomAvenue' => 'BUHEKA'],
            ['idQuartier' =>14,'nomAvenue' => 'KINGI'],
            ['idQuartier' =>19,'nomAvenue' => 'GAZIZA'],
            ['idQuartier' =>19,'nomAvenue' => 'GAKUBA'],
            ['idQuartier' =>14,'nomAvenue' => 'KIHIRA'],
            ['idQuartier' =>19,'nomAvenue' => 'NYARUBANDE'],
            ['idQuartier' =>14,'nomAvenue' => 'RUTSHURU'],
            ['idQuartier' =>19,'nomAvenue' => 'CYIRAMBO'],
            ['idQuartier' =>14,'nomAvenue' => 'KITOVU'],
            ['idQuartier' =>19,'nomAvenue' => 'BITEKO'],
            ['idQuartier' =>14,'nomAvenue' => 'BUTEMBO'],
            ['idQuartier' =>19,'nomAvenue' => 'BASUNGA'],
            ['idQuartier' =>14,'nomAvenue' => 'MONT HOYO'],
            ['idQuartier' =>19,'nomAvenue' => 'NYAKAGOZI'],
            ['idQuartier' =>3,'nomAvenue' => 'JACCARANDAS I'],
            ['idQuartier' =>3,'nomAvenue' => 'JACCARANDAS II'],
            ['idQuartier' =>3,'nomAvenue' => 'TULIPIERS 1'],
            ['idQuartier' =>3,'nomAvenue' => 'TULIPIERS 1'],
            ['idQuartier' =>3,'nomAvenue' => 'DU GOUVERNEUR'],
            ['idQuartier' =>3,'nomAvenue' => 'LA CORNICHE 2'],
            ['idQuartier' =>9,'nomAvenue' => 'LUBUTU'],
            ['idQuartier' =>3,'nomAvenue' => 'LA CORNICHE 3'],
            ['idQuartier' =>9,'nomAvenue' => 'KITONA'],
            ['idQuartier' =>3,'nomAvenue' => 'ORCHIDEES 1'],
            ['idQuartier' =>9,'nomAvenue' => 'KAMINA'],
            ['idQuartier' =>3,'nomAvenue' => 'ORCHIDEES 2'],
            ['idQuartier' =>3,'nomAvenue' => 'LA CORNICHE 1'],
            ['idQuartier' =>12,'nomAvenue' => 'WALIKALE'],
            ['idQuartier' =>3,'nomAvenue' => 'GREVILEAS II'],
            ['idQuartier' =>3,'nomAvenue' => 'GREVILEAS III'],
            ['idQuartier' =>3,'nomAvenue' => 'ACCASIAS I'],
            ['idQuartier' =>3,'nomAvenue' => 'ACCASIAS II'],
            ['idQuartier' =>3,'nomAvenue' => 'ACCASIAS III'],
            ['idQuartier' =>3,'nomAvenue' => 'BOUGAIVILLIER I'],
            ['idQuartier' =>3,'nomAvenue' => 'BOUGAIVILLIER II'],
            ['idQuartier' =>3,'nomAvenue' => 'BOUGAIVILLIER III'],
            ['idQuartier' =>3,'nomAvenue' => 'ROND-POINT I'],
            ['idQuartier' =>3,'nomAvenue' => 'ROND-POINT II'],
            ['idQuartier' =>3,'nomAvenue' => 'BLD. KANYAMUHANGA'],
            ['idQuartier' =>3,'nomAvenue' => 'BLD.KARISIMBI'],
            ['idQuartier' =>3,'nomAvenue' => 'BLD.SAKE'],
            ['idQuartier' =>3,'nomAvenue' => 'TOURISTE'],
            ['idQuartier' =>3,'nomAvenue' => 'BUTEMBO'],
            ['idQuartier' =>3,'nomAvenue' => 'MESSAGERS'],
            ['idQuartier' =>3,'nomAvenue' => 'BENI'],
            ['idQuartier' =>3,'nomAvenue' => 'PELICANS'],
            ['idQuartier' =>3,'nomAvenue' => 'DES IBIS I'],
            ['idQuartier' =>3,'nomAvenue' => 'DES IBIS II'],
            ['idQuartier' =>3,'nomAvenue' => 'DU PORT'],
            ['idQuartier' =>3,'nomAvenue' => 'MONT-GOMA'],
            ['idQuartier' =>3,'nomAvenue' => 'DES ECOLES'],
            ['idQuartier' =>18,'nomAvenue' => 'KAHONGOZI'],
            ['idQuartier' =>3,'nomAvenue' => 'WALIKALE'],
            ['idQuartier' =>3,'nomAvenue' => 'DU GOLF'],
            ['idQuartier' =>18,'nomAvenue' => 'NDJILI 1'],
            ['idQuartier' =>3,'nomAvenue' => 'CIRCULAIRE'],
            ['idQuartier' =>18,'nomAvenue' => 'NDJILI 2'],
            ['idQuartier' =>18,'nomAvenue' => 'CEAVU'],
            ['idQuartier' =>18,'nomAvenue' => 'MUSHEBERE'],
            ['idQuartier' =>18,'nomAvenue' => 'KALAMO'],
            ['idQuartier' =>18,'nomAvenue' => 'DU MARCHE'],
            ['idQuartier' =>18,'nomAvenue' => 'KITSHANGA'],
            ['idQuartier' =>18,'nomAvenue' => 'HEWA BORA 1'],
            ['idQuartier' =>18,'nomAvenue' => 'HEWA BORA 2'],
            ['idQuartier' =>18,'nomAvenue' => 'SHABINDU'],
            ['idQuartier' =>18,'nomAvenue' => 'RUTANDA'],
            ['idQuartier' =>18,'nomAvenue' => 'LUSHAGALA'],
            ['idQuartier' =>18,'nomAvenue' => 'RUSAYO 1'],
            ['idQuartier' =>18,'nomAvenue' => 'RUSAYO 2'],
            ['idQuartier' =>18,'nomAvenue' => 'MAENDELEO 2'],
            ['idQuartier' =>18,'nomAvenue' => 'DU 14 JANVIER'],
            ['idQuartier' =>18,'nomAvenue' => 'KASHAKA'],
            ['idQuartier' =>18,'nomAvenue' => 'BARAKA'],
            ['idQuartier' =>1,'nomAvenue' => 'TEST'],
            ['idQuartier' =>20,'nomAvenue' => 'BISHOSHA 2'],
            ['idQuartier' =>1,'nomAvenue' => 'Du mysée'],
            ['idQuartier' =>1,'nomAvenue' => 'Presidentiel'],
            ['idQuartier' =>2,'nomAvenue' => 'MAYIMOTO'],
            ['idQuartier' =>20,'nomAvenue' => 'NGANGI'],
            ['idQuartier' =>21,'nomAvenue' => 'M']
        ]);
    }




    
    


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('avenues');
    }
}
