<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTmatPartogrammeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tmat_partogramme', function (Blueprint $table) {
            $table->id();
            $table->foreignId('refDetailConst')->constrained('tdetailconsultation')->restrictOnUpdate()->restrictOnDelete();             
            $table->string('prov_As',5)->nullable();
            $table->string('prov_Has',5)->nullable();
            $table->string('prov_HZ',5)->nullable();
            $table->string('personne_Prevenir',5)->nullable();
            $table->string('adresse_prevenir',5)->nullable();
            $table->string('telephone_Prevenir',5)->nullable();
            $table->string('anamnese',5)->nullable();
            $table->string('motifconsultation',5)->nullable();
            $table->string('rh',5)->nullable();
            $table->string('status_AA',5)->nullable();
            $table->string('status_AS',5)->nullable();
            $table->string('status_SS',5)->nullable();
            $table->string('gatiste',5)->nullable();
            $table->string('parite',5)->nullable();
            $table->string('avortement',5)->nullable();
            $table->string('enfantEnVie',5)->nullable();
            $table->date('dateAdmission',5)->nullable();
            $table->string('heure1',5)->nullable();
            $table->datetime('date_DDr')->nullable();
            $table->datetime('date_DPA')->nullable();
            $table->string('femme_CDV',5)->nullable();
            $table->string('femme_testee',5)->nullable();
            $table->string('femme_resultat',5)->nullable();
            $table->string('regime',5)->nullable();
            $table->datetime('date_commencement')->nullable();
            $table->date('date_debut_travail',5)->nullable();
            $table->string('heure_debut_travail',5)->nullable();
            $table->string('antecedent_chirurgie',5)->nullable();
            $table->string('nbrEnfant_vivant',5)->nullable();
            $table->string('morts',5)->nullable();
            $table->string('morte_ne',5)->nullable();
            $table->string('mort_avant_7jours',5)->nullable();
            $table->datetime('date_dernierAcouchemnt')->nullable();
            $table->string('nbr_eutocie',5)->nullable();
            $table->string('nbr_dystocie',5)->nullable();
            $table->string('type_eutocie',5)->nullable();
            $table->string('nbre_bebe_poids',5)->nullable();
            $table->string('grossesse_multilple',5)->nullable();
            $table->string('cesarienne1',5)->nullable();
            $table->double('nbre_cesarienne')->nullable();
            $table->string('Annees1',5)->nullable();
            $table->string('indications1',5)->nullable();
            $table->string('Annees2',5)->nullable();
            $table->string('Indication2',5)->nullable();
            $table->string('Annee3',5)->nullable();
            $table->string('Indication3',5)->nullable();
            $table->string('Annee4',5)->nullable();
            $table->string('Indication4',5)->nullable();
            $table->string('Annee5',5)->nullable();
            $table->string('Indication5',5)->nullable();
            $table->double('poids_patrogramme')->nullable();
            $table->double('taille_patogramme')->nullable();
            $table->string('temperature_pato',5)->nullable();
            $table->string('pauls_pato',5)->nullable();
            $table->string('TA_pato',5)->nullable();
            $table->string('oedemes',5)->nullable();
            $table->string('conjoctive_coloree',5)->nullable();
            $table->string('conjoctive_pauls',5)->nullable();
            $table->string('etat_generale',5)->nullable();
            $table->string('systeme_respiratoire',5)->nullable();
            $table->string('systeme_circulatoire',5)->nullable();
            $table->string('systeme_digestif',5)->nullable();
            $table->string('systeme_urinaire',5)->nullable();
            $table->string('systeme_locomoteur',5)->nullable();
            $table->string('systeme_nerveux',5)->nullable();
            $table->string('Hu',5)->nullable();
            $table->string('presentation',5)->nullable();
            $table->string('position',5)->nullable();
            $table->string('bcf',5)->nullable();
            $table->string('contraction_uterines',5)->nullable();
            $table->string('mfa_presents',5)->nullable();
            $table->string('MFA_absants',5)->nullable();
            $table->string('bv_cal',5)->nullable();
            $table->string('col_efface',5)->nullable();
            $table->string('col_delate',5)->nullable();
            $table->string('col_particularite',5)->nullable();
            $table->string('poche_rampui',5)->nullable();
            $table->date('date_poche',5)->nullable();
            $table->string('heure_poche',5)->nullable();
            $table->string('LA_claire',5)->nullable();
            $table->string('verdatre',5)->nullable();
            $table->string('sanguinolent',5)->nullable();
            $table->string('jaunatre',5)->nullable();
            $table->string('pirulent',5)->nullable();
            $table->string('degre_haute',5)->nullable();
            $table->string('degre_amorcee',5)->nullable();
            $table->string('degre_fixee',5)->nullable();
            $table->string('dregre_engagee',5)->nullable();
            $table->string('bassin_bon',5)->nullable();
            $table->string('bassin_limite',5)->nullable();
            $table->string('bassin_retreci',5)->nullable();
            $table->string('bassin_asymetrique',5)->nullable();
            $table->string('result_GS',5)->nullable();
            $table->string('result_HC',5)->nullable();
            $table->string('result_HB',5)->nullable();
            $table->string('tDR_paludisme',5)->nullable();
            $table->string('result_GE',5)->nullable();
            $table->string('result_albuminurie',5)->nullable();
            $table->string('result_rpr1',5)->nullable();
            $table->string('result_urines',5)->nullable();
            $table->string('conclusion',5)->nullable();
            $table->string('pronostic',5)->nullable();
            $table->string('conduite_tenir',5)->nullable();
            $table->string('nom_examinateur',5)->nullable();
            $table->string('heure_examinateur',5)->nullable();
            $table->string('phase_lalente',5)->nullable();
            $table->string('phase_active',5)->nullable();
            $table->string('dilatation_complete',5)->nullable();
            $table->string('libelle_femme',5)->nullable();
            $table->string('accouchement_normal',5)->nullable();
            $table->string('acouchement_heure',5)->nullable();
            $table->string('gemellaire',5)->nullable();
            $table->string('dechirure',5)->nullable();
            $table->string('degre_acouchement',5)->nullable();
            $table->string('apisiotomie',5)->nullable();
            $table->string('sature_par',5)->nullable();
            $table->string('ventouse',5)->nullable();
            $table->string('forceps',5)->nullable();
            $table->string('symphyseotamie',5)->nullable();
            $table->string('cesarienne2',5)->nullable();
            $table->string('indication',5)->nullable();
            $table->string('accouchement',5)->nullable();
            $table->string('assistant',5)->nullable();
            $table->string('ne_date',5)->nullable();
            $table->string('ne_heure',5)->nullable();
            $table->string('ne_sexe',5)->nullable();
            $table->string('maintien',5)->nullable();
            $table->string('taxillaire',5)->nullable();
            $table->string('crede',5)->nullable();
            $table->string('sein_cordon',5)->nullable();
            $table->string('mise_au_sein',5)->nullable();
            $table->double('ne_poids')->nullable();
            $table->double('ne_taille')->nullable();
            $table->string('ne_pc',5)->nullable();
            $table->string('ocytocine',5)->nullable();
            $table->string('delivrance_heure',5)->nullable();
            $table->string('traction_cordon',5)->nullable();
            $table->string('message_delivrance',5)->nullable();
            $table->string('delivrance_spontanee',5)->nullable();
            $table->string('spontanee_heure',5)->nullable();
            $table->string('delivrance_artificielle',5)->nullable();
            $table->string('atificielle_heure',5)->nullable();
            $table->string('placenta_complet',5)->nullable();
            $table->string('placenta_incomplet',5)->nullable();
            $table->string('aspect_delivrance',5)->nullable();
            $table->string('membranes_complet',5)->nullable();
            $table->string('membranes_incomplet',5)->nullable();
            $table->string('hemo_physidagique',5)->nullable();
            $table->string('hemo_pathologique',5)->nullable();
            $table->string('remination',5)->nullable();
            $table->string('stimulation',5)->nullable();
            $table->string('aspiration',5)->nullable();
            $table->string('ventilation',5)->nullable();
            $table->string('autres_remination',5)->nullable();
            $table->string('vid_k1',5)->nullable();
            $table->string('antibotique',5)->nullable();
            $table->string('Arv',5)->nullable();
            $table->string('autreTraitement_donne',5)->nullable();
            $table->string('soins_post_partum',5)->nullable();
            $table->string('signes_danger1',5)->nullable();
            $table->string('utilisation_micd',5)->nullable();
            $table->string('planification_familiale',5)->nullable();
            $table->string('nutrition',5)->nullable();
            $table->string('diagnostic_precoce',5)->nullable();
            $table->string('traitement_ARV',50)->nullable();
            $table->string('consultion_suiviere',5)->nullable();
            $table->string('allaitement_materiel',5)->nullable();
            $table->string('hygiene_soins',5)->nullable();
            $table->string('recommandation',5)->nullable();
            $table->string('signes_danger2',5)->nullable();
            $table->string('consultation_suivi_ne',5)->nullable();
            $table->string('fer_falates',5)->nullable();
            $table->string('mebendazole',5)->nullable();
            $table->string('sultadoxine',5)->nullable();
            $table->string('dormir_mld_mere',5)->nullable();
            $table->string('vaccine_anti_tetuiquie',5)->nullable();
            $table->string('vitamineA',5)->nullable();
            $table->string('test_RPR',5)->nullable();
            $table->string('traitement_prophylaxie',5)->nullable();
            $table->string('bCG_vpo',5)->nullable();
            $table->string('result_rPR2',5)->nullable();
            $table->string('profilaxie_TB',5)->nullable();
            $table->string('dormir_mlcd_de',5)->nullable();
            $table->string('cas_risque_infection',5)->nullable();
            $table->string('prophylaxie_Arv_ne',5)->nullable();
            $table->string('author',5);
            $table->string('deleted')->default('NON');
            $table->string('author_deleted')->default('user'); 
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tmat_partogramme');
    }
}
