<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTfinActesmedecinTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tfin_actesmedecin', function (Blueprint $table) {
            $table->id();
            $table->foreignId('refUnite')->constrained('tfin_uniteproduction')->restrictOnUpdate()->restrictOnDelete();
            $table->foreignId('refSscompte')->constrained('tfin_ssouscompte')->restrictOnUpdate()->restrictOnDelete();
            $table->string('nom_acte');
            $table->double('prix_acte')->default(0);
            $table->double('prix_convention')->default(0);
            $table->string('code_acte')->default('000');
            $table->string('author')->default('Admin');
            $table->string('deleted')->default('NON');
            $table->string('author_deleted')->default('user'); 
            $table->timestamps();
        });

        DB::table('tfin_actesmedecin')->insert([
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'INTUBATION  +VENTILLATION  MECANIQUE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'INTUBATION +VENTILLATION + VENTILLATION  ARTIFICIELLE AVEC  RESPIRATEUR/jour'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'NEBULISATION'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Poche de sang'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Phototherapie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Sejour en SI'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TDS en  SI'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'NURSING en SI'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cure chalazion'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Lavage de voieslacrymal'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cure pterigion'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction corps estranger occulaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verre progrressif photogray organiques'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verre progressif organique'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verre organique unifocaux'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verres organiques pherocylindrique unifocaux'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verres organiques bifocaux'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verres mierals sphere cylindriques'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verres progressif minerale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verre photogray unifocau minerals'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Verre photogray bifocaux minerals'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Redressement monture'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Reparation monture'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Pochette monture'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture silouette'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture plastique 2em Qlte'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture plastique ler  qlte'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture metalique ler  qlte'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture metalique 2em qlte'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture lecture de pres'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture plastique homme'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Monture plastique dame'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Montage  simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Montage complique'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Montage tres complique'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Lens cleaner'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Demi monture moyenne'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CRPG HMO PROG Blue cut 90'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CRPG HMC Bi focal 55'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PGX glass Prog 65'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CRPG HMC PROG 70'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Lamelle'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Branche monture'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CONSULTATION PRE ANESTHESIQUE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Anesthesie et reanimation'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Anesthesie locale (contact cutane ou par infiltration)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Corset plâtre'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CRP QUANTITATIVE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Jambe/bras long (long bone)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CRP QUALITATIVE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Jambe/bras court'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'HEPATITE A'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Coude (elbow)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Curo pédieux (thigh – foot)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'HEPATITE B Ag'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'HEPATITE C Ag'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'VDRL/RPR'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Curo jambe'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TPHA'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Plâtre en L'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TOXOPLASMA'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'H PYLORI'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Plâtre palmier'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Ablation plâtre'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Fenestration / renforcement'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'RUBEOLE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Corset minerve'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'ASLO'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Corset simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CHLAMIDIA Ag'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Corset de saut'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Corset thoraco brachial'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'FACTEUR RHUMATOIDE(FR)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Attelle curo jambier'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Attelle curo pédieux'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Attelle brachio palmaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Attelle palmaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Pansement ordinaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Infiltration'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CIRCONCISION'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POTASIUM'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'MAGNESUIM'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'SODUIM'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CHLORE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'IONOGRAME SIMPLE(Na+ K+ CL-)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'OESTRADIOL'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'OESTRIOL'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PROGESTERONE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TSH'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'FSH'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PROLACTINE(PRO)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'HORMONE DE CROISSANCE(=>GH)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'LH'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'B HCG quantitatif'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'T3(iodothyronine'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'T4(tyroxine)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TESTOSTERONE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'D-DIMER'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'ALFA FOETOPROTEINE(AFP)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PSA(prostaticspecificantigen'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'SALLE DE REVEil'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'URGENCE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Drainage abces superficiel(acte +anesthesie)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Lipomectomie(actes +anesthesie)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Drainage thoracique(actes + anesthesie)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cure oclusion intestinale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Petite chirurgie (plaie simple)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Hernioraphieinguinale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cure d\'une hernie ombilicale ou de la ligne blanche'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cure d\'eventration Complique'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Detorsiontesticulaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Desinvagination'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Drainage abceshepatique avec laparotomie et autres abces profondes (abcessplenique,abces sous phrenique, abces renal'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Orchidopexie et abaissement du testicule'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Resection  intestinale+anastomose'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Colostomie,'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cholecystectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Splenectomie, Hysterectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prostatectomies'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Tumorectomie du sein(extraction du nodule de sein)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Tumorectomie du sein(extraction du nodule de sein)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction du nodule de sein simple sous AL'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent posterieur simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent immobile'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Mastectomie totale +curageganglionaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation provisoire Zoe'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction racine'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cure d\'une fistule anale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Incision et drainage (phlegmon amydalien)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Hemoroidectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Incision et drainage dent abcès'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Ablation masse abdominale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CORRECTION PIED BOT'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CORRECTION DE GENOU VAGUM'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CORRECTION PIED EQUIN'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation et ionomére de verre'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation à l oxyphosphate'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cavitologie & Obturation et amalgame 2 face'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cavitologie & Obturation et amalgame 3 face'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation composite 1 face'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation composite 3 face'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Coiffage pulpaire direct'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Coiffage pulpaire indirect'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Pulpotomie, pulpectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Traitement endocanalaire: 1 canal'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CORRECTION DE GENOU VAGUM'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prémolaire: 2 canaux'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'OESTEOMIE DE CORRECTION'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TRANSFERT DES TENDONS'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POSE D UN CCM FEMORICE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POSE D UN CCM TIBISALE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Molaire: 3 et 4 canaux'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation canalaire dent'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Apicectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Traitement alvéolite sèche dent'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POSE DE FIXATEUR EXTERNE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Traitement alvéolite humide dent'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Gingivectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Curetage poche parodontale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Polissage (brossette + pâte)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Immobilisation dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POSE DE PLAQUE COUDE DE CONDYLE FEMORALE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Réduction ATM'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Réparation prothèse dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Confection PAP / élément'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Confection App. ODF amovible'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Confection A phtes (application nitrate d argent)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Biopsie (dentisterie)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Suture plaie buccale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extirpation calcul salivaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Reconstitution coronaire: tenon + composite'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Immobilisation bimaxillaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation composite 2 face'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'RX Radio Dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Rx recto alvéolaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Traitement ODF Orthopédie-dento-faciale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent de lait sans anésthesie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent de lait avec anésthesie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POSE D UNE PLAQUE VISEEE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dentaire simple sous anésthesie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent ectopique'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent surnuméraire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PIROGAGE CHIRURGICALE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent impactée'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'LEVER D EMBARRURES'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'CERCLAGE OLEOCRANIEN'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TREPANATION ET EMBARRURE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'POSE D UN FF'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'EMBROCHAGE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'REDUCTION D UNE LUXATION ORTHOPEDIQUE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'REDUCTION SANGLANTE D UNE LUXATION'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PIROGAGE ET CURETAGE OSSEUX'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'GRIFFE OSSEUX'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'DEBRIDEMENT DES TISSUS DEVITALISES'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'DRAINAGE THORACIQUE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'SUTURE PRIMAIRE OSSEUSE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'TRACTION INTER OSSEUSE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'SKIN TRACTION'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PLATRE PELVICRIRO PEDIEUX'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PLATRE CRIORO PEDIEUX'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PLATRE BRACHIO ANTE PALMAIRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PLATRE THARACO BRANCHIALE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'BOTTE PLATRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'MINERVA PLATRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'DESAULT PLATRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PLATRE BRACHIO ANTE PALMAIRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'MACHETTE PLATRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'DASAULT PLATRE'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'BANDAGE EN HUIT'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'INFILTRATION'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'PANSEMENT'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction des molaires'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction des canines et pre molaires'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction des incisives adultes'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent frontale simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent posterieur simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent immobile'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation provisoire Zoe'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction racine'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Incision et drainage (phlegmon amydalien)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Incision et drainage dent abcès'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation et ionomére de verre'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation à l oxyphosphate'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Cavitologie & Obturation et amalgame 2 face'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent de sagesse'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent compliquée'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent fracturée'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent fracturée ailleurs'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Sequestrectomie maxillaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Epulicectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Operculectomie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Réduction de la luxation temporo- mandibulaire ou Nelation'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Immobilisation de fracture mono maxillaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Réparation de morsure de la langue'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Réparation de blessure labiale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Traitement ODF Orthopédie-dento-faciale'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent de lait sans anésthesie'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent incluse'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Curétage alvéolaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Pansement sédatif sous eugénol'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Detartrage partiel (simple)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Détartrage complet (complexe)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation définitive par face dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Obturation esthétique par face dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Soins de l alvéolite post-extractionnelle dent'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Couronne à pivot + ADAPTIC (traitement canalaire) Fixation'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extirpation kyste para-dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Dévitalisation + Cavitologie& Obturation définitive'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Rebasage du dentier > et/ou<'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prise d empreinte en alginate'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Coulée de modele en plâtre'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Elément pour dentier mobile'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Réparation du dentier'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Scellement de couronne'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Meulage dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Kystectomie simple (dent)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Dent à pivot'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Extraction dent simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Soins post extractionnels'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prothèse à un élément'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prothèse à deux éléments'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prothèse à quatre éléments'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prothèse à cinq éléments'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Blanchissement des dents avec composit lelt'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Blanchissement des dents fluoree lelt'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Blanchissement des dents non fluoree (cleaningwhitening)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'orthodontie complexe'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prothese total par dent'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'courone artificielle (jacket crawn) resin'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'courone artifielle Uacket crawn) porcelain'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Detartrage complet'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Detartrage simple'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Detartrage (oral prophylaxie)'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Prothèse dentaire'],
            ['refUnite' =>1,'refSscompte' =>4,'nom_acte' => 'Orthodontie simple']

        ]);





    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tfin_actesmedecin');
    }
}
